In [5]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [6]:
data_raw = pd.DataFrame({'Fruit': ['Apple', 'Banana', 'Orange','Apple', 'Kiwi', 'Grape'],
                       'Color': ['Red', 'Yellow', 'Orange','Red', 'Green', 'Purple']})

# Label Encoding

In [7]:
data = data_raw.copy()
le = LabelEncoder()
data['Color_Encoded'] = le.fit_transform(data['Color'])
print(data)

    Fruit   Color  Color_Encoded
0   Apple     Red              3
1  Banana  Yellow              4
2  Orange  Orange              1
3   Apple     Red              3
4    Kiwi   Green              0
5   Grape  Purple              2

# One-Hot Encoder

In [19]:
#Import Libraries
from sklearn.preprocessing import OneHotEncoder

#Fitting OHE
data = data_raw.copy()
ohe = OneHotEncoder(handle_unknown='ignore')
encoding_col = ['Fruit','Color']
data_encoded = ohe.fit_transform(data[encoding_col]).toarray()
data_encoded_df = pd.DataFrame(data_encoded, columns=ohe.get_feature_names(encoding_col))
data_encoded = pd.concat([data, data_encoded_df], axis=1)

print(data_encoded)

    Fruit   Color  Fruit_Apple  Fruit_Banana  Fruit_Grape  Fruit_Kiwi  \
0   Apple     Red          1.0           0.0          0.0         0.0
1  Banana  Yellow          0.0           1.0          0.0         0.0
2  Orange  Orange          0.0           0.0          0.0         0.0
3   Apple     Red          1.0           0.0          0.0         0.0
4    Kiwi   Green          0.0           0.0          0.0         1.0
5   Grape  Purple          0.0           0.0          1.0         0.0

   Fruit_Orange  Color_Green  Color_Orange  Color_Purple  Color_Red  \
0           0.0          0.0           0.0           0.0        1.0
1           0.0          0.0           0.0           0.0        0.0
2           1.0          0.0           1.0           0.0        0.0
3           0.0          0.0           0.0           0.0        1.0
4           0.0          1.0           0.0           0.0        0.0
5           0.0          0.0           0.0           1.0        0.0

   Color_Yellow
0           0.0
1           1.0
2           0.0
3           0.0
4           0.0
5           0.0

/opt/conda/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

# Ordinal Encoder

In [30]:
from sklearn.preprocessing import OrdinalEncoder

In [31]:
data = pd.DataFrame({'education_level':['High School','Bachelor\'s Degree',
                                        'Master\'s Degree','PhD','High School','Master\'s Degree']})

category_ranks = {'High School': 1, 
                  'Bachelor\'s Degree': 2, 
                  'Master\'s Degree': 3, 
                  'PhD': 4}

In [32]:
ordinal_encoder = OrdinalEncoder(categories=[list(category_ranks.keys())], dtype=int)
data['education_level_encoded'] = ordinal_encoder.fit_transform(data[['education_level']])

print(data)

     education_level  education_level_encoded
0        High School                        0
1  Bachelor's Degree                        1
2    Master's Degree                        2
3                PhD                        3
4        High School                        0
5    Master's Degree                        2